package Views;

import java.applet.AudioClip;
import java.util.Random;

public class ViewUniversitarios extends javax.swing.JDialog {
    
    private AudioClip convidados;
    private int nivel;

    public ViewUniversitarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public ViewUniversitarios(java.awt.Frame parent, boolean modal, int correta, int nivel) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.nivel = nivel;
        
        convidados = java.applet.Applet.newAudioClip(getClass().getResource("/sons/convidados.wav"));
        convidados.play();
        
        Random universitario = new Random();
        
        if(this.nivel==1){
            if(universitario.nextInt(100)+1<96) txtUni1.setText(String.valueOf(correta));
            else txtUni1.setText(String.valueOf(universitario.nextInt(4)+1));
            if(universitario.nextInt(100)+1<91) txtUni2.setText(String.valueOf(correta));
            else txtUni2.setText(String.valueOf(universitario.nextInt(4)+1));
            
            txtUni3.setText(String.valueOf(correta));
        }else if(this.nivel==2){
            if(universitario.nextInt(100)+1<81) txtUni1.setText(String.valueOf(correta));
            else txtUni1.setText(String.valueOf(universitario.nextInt(4)+1));
            if(universitario.nextInt(100)+1<86) txtUni2.setText(String.valueOf(correta));
            else txtUni2.setText(String.valueOf(universitario.nextInt(4)+1));
            if(universitario.nextInt(100)+1<91) txtUni3.setText(String.valueOf(correta));
            else txtUni3.setText(String.valueOf(universitario.nextInt(4)+1));
        }else{
            if(universitario.nextInt(100)+1<31) txtUni1.setText(String.valueOf(correta));
            else txtUni1.setText(String.valueOf(universitario.nextInt(4)+1));
            if(universitario.nextInt(100)+1<71) txtUni2.setText(String.valueOf(correta));
            else txtUni2.setText(String.valueOf(universitario.nextInt(4)+1));
            if(universitario.nextInt(100)+1<81) txtUni3.setText(String.valueOf(correta));
            else txtUni3.setText(String.valueOf(universitario.nextInt(4)+1));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUni1 = new javax.swing.JLabel();
        txtUni2 = new javax.swing.JLabel();
        txtUni3 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 380));
        setPreferredSize(new java.awt.Dimension(600, 380));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 380));
        getContentPane().setLayout(null);

        txtUni1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        txtUni1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtUni1);
        txtUni1.setBounds(160, 40, 50, 50);

        txtUni2.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        txtUni2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtUni2);
        txtUni2.setBounds(330, 40, 60, 50);

        txtUni3.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        txtUni3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtUni3);
        txtUni3.setBounds(500, 40, 60, 50);

        btnOk.setBackground(new java.awt.Color(204, 204, 204));
        btnOk.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnOk.setText("OK");
        btnOk.setFocusable(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(510, 303, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/layoutUniversitarios.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUniversitarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ViewUniversitarios dialog = new ViewUniversitarios(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtUni1;
    private javax.swing.JLabel txtUni2;
    private javax.swing.JLabel txtUni3;
    // End of variables declaration//GEN-END:variables
}
